namespace JakDojadeMCP.Server.Models;

public record FindRoute(string StartPointLatitude,
    string StartPointLongitude,
    string EndPointLatitude,
    string EndPointLongitude,
    string? Agglomeration,
    string? Date,
    string? Hour,
    bool? IsArrival,
    int? RouteCount,
    int? RouteIndex,
    string? Type,
    bool? IncludeRoadCoordinates,
    bool? Test,
    bool? AvoidChanges,
    bool? AvoidBuses,
    string? ProhibitedVehicles,
    string? ProhibitedOperators,
    bool? AvoidExpresses,
    bool? AvoidZonal,
    bool? OnlyLowFloor,
    int? RoadsOn,
    string? ProhibitedLines,
    string? PreferLines
);